### ISSUE TITLE
Cannot detect device on real iPhone

### ISSUE THREAD

**Issue by nguyenanhtuan-19127614** [ConnectSDK/Connect-SDK-iOS-Core#91]
Hi, i'm currently using ConnectSDK/Core newest version from CocoaPod and i cannot find any device when i'm using real iPhone, you guys have any advice? Wish to have some help.

**Comment by sivaprasadkv** [comment]
This issue has been resolved by enabling "Multicast Networking" (com.apple.developer.networking.multicast).
Request Apple to enable this advanced capability in your developer account for a particular Apple identifier. 
Provide proper justification on using this capability in your app.

URL to make a request is: https://developer.apple.com/contact/request/networking-multicast

Ones Apple approved, enable this capability to app's bundle identifier in your developer certificates account.
After this, add "com.apple.developer.networking.multicast" = YES in your entitlement file in your project.

After all this, your app discovers all the devices immediately.
Enjoy Coding! :)

**Comment by nguyenanhtuan-19127614** [comment]
> This issue has been resolved by enabling "Multicast Networking" (com.apple.developer.networking.multicast). Request Apple to enable this advanced capability in your developer account for a particular Apple identifier. Provide proper justification on using this capability in your app.
> 
> URL to make a request is: https://developer.apple.com/contact/request/networking-multicast
> 
> Ones Apple approved, enable this capability to app's bundle identifier in your developer certificates account. After this, add "com.apple.developer.networking.multicast" = YES in your entitlement file in your project.
> 
> After all this, your app discovers all the devices immediately. Happy Coding! :)

It works really well, thanks man, struggle with this for a while haha
